server:
  port: 8085

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

  redis:
    host: localhost #redis服务器地址
    port: 6379 #端口号
    database: 0 #数据库索引，16个，默认0
    password:  #redis服务器连接密码，默认为空
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 3000ms # 连接超时时间（毫秒）

# 自定义redis key
redis:
  database: wymall
  key:
    authCode:
      prefix: "ums:authCode:"
      expire: 120