server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

mybatis:
  mapper-locations:
   - classpath:dao/*.xml
   - classpath*:com/**/mapper/*.xml

# 打印sql
logging:
  level:
    com.cjs.wymall.mapper : debug
