server:
  port: 8080


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123

mybatis:
  mapper-locations:
   - classpath:dao/*.xml
   - classpath*:com/**/mapper/*.xml


#jwt
jwt:
  tokenHeader: Authorization #jwt存储的请求头
  secret: wymall-admin-secret #jwt加密时使用的密钥
  expiration: 604800 #jwt的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #jwt token的前缀(持票人)

# 打印sql
logging:
  level:
    com.cjs.wymall.mapper : debug
